name: main branch protection
# This workflow is triggered on PRs to main branch on the repository
# It fails when someone tries to make a PR against the main branch from a branch other than QA
on:
  pull_request_target:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: true
    steps:
      # PRs to the main branch are only OK if they are coming from he QA branch
      - name: Check PRs
        if: github.repository == 'BarryDigby/branch_protection'
        run: |
          { [[ ${{github.event.pull_request.head.repo.full_name }} == BarryDigby/branch_protection ]] && [[ $GITHUB_HEAD_REF == "QA" ]]; }

      # If the above check failed, post a comment on the PR explaining the failure
      # NOTE - this doesn't currently work if the PR is coming from a fork, due to limitations in GitHub actions secrets
      - name: Post PR comment
        if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## This PR is against the `main` branch :x:

            * Do not close this PR
            * Click _Edit_ and change the `base` to `QA`
            * This CI test will remain failed until you push a new commit

            ---

            Hi @${{ github.event.pull_request.user.login }},

            It looks like this pull-request is has been made against the [${{github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `main` branch.
            The `main` branch should always contain code from the latest release.
            Because of this, PRs to `main` are only allowed if they come from the [${{github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `QA` branch.

            You do not need to close this PR, you can change the target branch to `QA` by clicking the _"Edit"_ button at the top of this page.
            Note that even after this, the test will continue to show as failing until you push a new commit.

            Thanks again for your contribution!
        
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false