name: branch protection
# This workflow is triggered on PRs to the repository.
# Follows main <- QA <- DEV <- DEV_* (local branch)
# It uses pull_request_target (and not 'pull_request') to enforce the workflow is run from a trusted source
# i.e the BASE and not from the incoming merge, which could be potentially malicious. 
on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check PRs
        if: github.repository == 'BarryDigby/branch_protection'
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" != "QA" ]]; then
            exit 1
          fi

          if [[ "${{ github.event.pull_request.base.ref }}" == "QA" && "${{ github.event.pull_request.head.ref }}" != "DEV" ]]; then
            exit 1
          fi
        
          if [[ "${{ github.event.pull_request.base.ref }}" == "DEV" && "${{ github.event.pull_request.head.ref }}" != DEV_* ]]; then
            exit 1
          fi

      # If the above check failed, post a comment on the PR explaining the failure
      # NOTE - this doesn't currently work if the PR is coming from a fork, due to limitations in GitHub actions secrets
      - name: Post PR comment
        if: failure()
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message: |
            ## This PR is against the `main` branch :x:

            * Do not close this PR
            * Click _Edit_ and change the `base` to `QA`
            * This CI test will remain failed until you push a new commit

            testing some regex here:
            It looks like you are pushing from the branch: ${{ github.event.pull_request.head.ref }}
            

            ---

            Hi @${{ github.event.pull_request.user.login }},

            It looks like this pull-request is has been made against the [${{github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `main` branch.
            The `main` branch should always contain code from the latest release.
            Because of this, PRs to `main` are only allowed if they come from the [${{github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `QA` branch.

            You do not need to close this PR, you can change the target branch to `QA` by clicking the _"Edit"_ button at the top of this page.
            Note that even after this, the test will continue to show as failing until you push a new commit.

            Thanks again for your contribution!
        
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false