name: branch protection
# This workflow is triggered on PRs to the repository.
# Follows main <- QA <- DEV <- DEV_* (local branch)
# It uses pull_request_target (and not 'pull_request') to enforce the workflow is run from a trusted source
# i.e the BASE and not from the incoming merge, which could be potentially malicious. 
on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check PRs
        if: github.repository == 'BarryDigby/branch_protection'
        run: |
          declare -A branch_map=( ["main"]="QA" ["QA"]="DEV" ["DEV"]="DEV_*" )
          incoming_branch="${{ github.event.pull_request.head.ref }}"
          target_branch="${{ github.event.pull_request.base.ref }}"
          expected_branch=${branch_map["$target_branch"]}

          { [[ ${{github.event.pull_request.head.repo.full_name }} == BarryDigby/branch_protection ]] && [[ "$incoming_branch" != "$expected_branch" ]]; }

          echo "::set-output name=incoming_branch::$incoming_branch"
          echo "::set-output name=target_branch::$target_branch"
          echo "::set-output name=expected_branch::$expected_branch"
        

      # If the above check failed, post a comment on the PR explaining the failure
      # NOTE - this doesn't currently work if the PR is coming from a fork, due to limitations in GitHub actions secrets
      - name: Post PR comment
        if: failure()
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message: |
            ## This PR is against the `${{steps.checks.outputs.target_branch}}` branch :x:

            * Do not close this PR
            * Click _Edit_ and change the `base` to `${{steps.checks.outputs.expected_branch}}`
            * This CI test will remain failed until you push a new commit

            ---

            Hi @${{ github.event.pull_request.user.login }},

            It looks like this pull-request is has been made against the [${{github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `${{steps.checks.outputs.target_branch}}` branch.
            The `${{steps.checks.outputs.target_branch}}` branch should always contain code from the `${{steps.checks.outputs.expected_branch}}` branch.
            Because of this, PRs to `${{steps.checks.outputs.target_branch}}` are only allowed if they come from the [${{github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `${{steps.checks.outputs.expected_branch}}` branch.

            You do not need to close this PR, you can change the target branch to `${{steps.checks.outputs.expected_branch}}` by clicking the _"Edit"_ button at the top of this page.
            Note that even after this, the test will continue to show as failing until you push a new commit.

            Thanks again for your contribution!
        
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false