name: branch protection
# This workflow is triggered on PRs to the repository.
# Follows main <- QA <- DEV <- DEV_* (local branch)
# It uses pull_request_target (and not 'pull_request') to enforce the workflow is run from a trusted source
# i.e the BASE and not from the incoming merge, which could be potentially malicious. 
on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check PRs
        id: checks
        if: github.repository == 'BarryDigby/branch_protection'
        run: |
          target_branch="${{ github.event.pull_request.base.ref }}"
          incoming_branch="${{ github.event.pull_request.head.ref }}"
          declare -A branch_array=( ["main"]="QA" ["QA"]="DEV" ["DEV"]="DEV_*" )
          expected_incoming_branch=${branch_map["$target_branch"]}

          for key in "${!branch_map[@]}"; do
              if [[ "${branch_map[$key]}" = "${expected_branch}" ]]; then
                  recommended_target_branch=$key
              fi
          done

          echo "The name of the incoming branch is: $incoming_branch"
          echo "The name of the target branch is: $target_branch"
          echo "The expected incoming branch for the target branch is: $expected_incoming_branch"
          echo "The recommended target branch for the incoming branch is: $recommended_target_branch"

          echo "::set-output name=INCOMING_BRANCH::$incoming_branch"
          echo "::set-output name=TARGET_BRANCH::$target_branch"
          echo "::set-output name=EXPECTED_BRANCH::$expected_branch"
        
          { [[ ${{github.event.pull_request.head.repo.full_name }} == BarryDigby/branch_protection ]] && [[ "$incoming_branch" == "$expected_branch" ]]; }

      # If the above check failed, post a comment on the PR explaining the failure
      # NOTE - this doesn't currently work if the PR is coming from a fork, due to limitations in GitHub actions secrets
      - name: Post PR comment
        if: failure()
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message: |
            ## This PR is against the `${{ steps.checks.outputs.TARGET_BRANCH }}` branch :x:

            * Do not close this PR
            * Click _Edit_ and change the `base` to `${{ steps.checks.outputs.EXPECTED_BRANCH }}`
            * This CI test will remain failed until you push a new commit

            ---

            Hi @${{ github.event.pull_request.user.login }},

            It looks like this pull-request is has been made against the [${{ github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `${{ steps.checks.outputs.TARGET_BRANCH }}` branch.
            The `${{ steps.checks.outputs.TARGET_BRANCH }}` branch should always contain code from the `${{ steps.checks.outputs.EXPECTED_BRANCH }}` branch.
            Because of this, PRs to `${{ steps.checks.outputs.TARGET_BRANCH }}` are only allowed if they come from the [${{ github.event.pull_request.head.repo.full_name }}](https://github.com/${{github.event.pull_request.head.repo.full_name }}) `${{ steps.checks.outputs.EXPECTED_BRANCH }}` branch.

            You do not need to close this PR, you can change the target branch to `${{ steps.checks.outputs.EXPECTED_BRANCH }}` by clicking the _"Edit"_ button at the top of this page.
            Note that even after this, the test will continue to show as failing until you push a new commit.

            Thanks again for your contribution!
        
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false